# Generated by Django 5.1.4 on 2024-12-31 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
