# Generated by Django 5.1.4 on 2025-01-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(upload_to='media/services/'),
        ),
    ]
