# Generated by Django 5.1.4 on 2025-01-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_alter_services_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaleproduct',
            name='image',
            field=models.ImageField(upload_to='media/wholesale/'),
        ),
    ]
