# Generated by Django 5.1.4 on 2025-01-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_alter_wholesaleproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaleproduct',
            name='category',
        ),
    ]
