# Generated by Django 5.1.4 on 2025-01-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0009_mpesapayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_id',
            field=models.CharField(blank=True, editable=False, max_length=36),
        ),
    ]
